In [53]:
import numpy as np


In [54]:
arr1 = np.array([20,30,40,50])
arr2 = np.array([30,40,60,70])
print(arr1+arr2)
print(np.add(arr1,arr2))





[ 50  70 100 120]
[ 50  70 100 120]


In [56]:
arr1 = np.array([20,30,40,50])
arr2 = np.array([30,40,60,70])
print(arr1-arr2)
print(np.subtract(arr1,arr2))

[-10 -10 -20 -20]
[-10 -10 -20 -20]


In [57]:
arr1 = np.array([20,30,40,50])
arr2 = np.array([30])
print(np.power(arr1,arr2))



[-8070450532247928832  2565992168703393792                    0
  5878960461428293632]


In [60]:
arr1 = np.array([20,30,40,50])
print(np.sqrt(arr1))

[4.47213595 5.47722558 6.32455532 7.07106781]
