In [35]:
import numpy as np


In [46]:
arr = np.array ([[20,30,40,50],[30,40,60,70],[80,90,60,10]])
print(np.shape(arr))
print(np.size(arr))
print(np.ndim(arr))
print(arr.dtype)
print(len(arr))
print(arr.astype(int))




(3, 4)
12
2
int64
3
[[20 30 40 50]
 [30 40 60 70]
 [80 90 60 10]]
